### ISSUE TITLE
error when run "python main.py --dataset="parta" --gpu=2 --start-epoch=0 --epochs=30"

### ISSUE THREAD

**Issue by xiao-xiao-jin** [val-iisc/lsc-cnn#10]
python main.py --dataset="parta" --gpu=2 --start-epoch=0 --epochs=30
In data_reader.__init__: Can't read meta data in ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30; call create_dataset_files.
{'test': ['../dataset/ST_partA/test_data/images', '../dataset/ST_partA/test_data/ground_truth'], 'train': ['../dataset/ST_partA/train_data/images', '../dataset/ST_partA/train_data/ground_truth']} <data_reader.DataReader object at 0x7f2d2b928ef0>
CREATING DATASET...
In data_reader.create_dataset_files: Deleted old ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test created.
In data_reader.create_dataset_files: Deleted old ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/train.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/train created.
In data_reader.create_dataset_files: Deleted old ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test_valid.
In data_reader.create_dataset_files: ../dataset/stparta_dotmaps_predscale0.5_rgb_ddcnn++_test_val_30/test_valid created.
Processing IMG_1.jpg ...
Traceback (most recent call last):
  File "main.py", line 1108, in <module>
    train()
  File "main.py", line 1029, in train
    test_batch_size=4)
  File "/home/fire/lsc-cnn/data_reader.py", line 200, in create_dataset_files
    self._dump_all_test_images(set_name)
  File "/home/fire/lsc-cnn/data_reader.py", line 826, in _dump_all_test_images
    data = self._read_image_and_gt_prediction(paths, file_name, kernel)
  File "/home/fire/lsc-cnn/data_reader.py", line 789, in _read_image_and_gt_prediction
    'GT_' + tmp + '.mat'))
  File "/home/fire/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/fire/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

**Comment by pvskand** [comment]
I guess you'd have to replace `GT` with `GT_`. For further help refer - https://github.com/val-iisc/lsc-cnn/blob/master/data_reader.py#L789
