### ISSUE TITLE
Facing error in offset_sum

### ISSUE THREAD

**Issue by aqu1122** [val-iisc/lsc-cnn#14]
hey, thanks for opensource.
![a](https://user-images.githubusercontent.com/57431212/68290812-91070300-00c3-11ea-9c6e-031d8f37ca9d.jpg)

 i am beginner to this. maybe this error will very basic but i really don't know how to handle this. 

line 15
    def offset_sum(long long [:, :] sorted_idx, double [:, :] d, long long n, long long m, long long max_dist):
                           ^
SyntaxError: invalid syntax

**Comment by pvskand** [comment]
Hello,
Did you compile the `mle_function` (running the `script.sh` file in `utils/mle_function`)? Also make sure to use `python3` to compile the script. Let me know if you still have a problem after this.

**Comment by aqu1122** [comment]
solved... thank you so much :)

**Comment by sanakousar00** [comment]
> solved... thank you so much :)

how you solved ??????????????????????????????
