### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by hendl** [val-iisc/lsc-cnn#16]
Hi

I adjusted the code to train my own dataset. 
What is the ideal dataset size you would recommend to train with?

I tried to train with a reduced openimage dataset with 132GB of pictures and it created about 2.2TB in the preprocessing and it's still processing pictures. Would you recommend a smaller dataset?

Thanks

**Comment by pvskand** [comment]
Hello,
Preprocessing takes time because it dumps patches for every image to be used during the training (and testing). If you dataset is large - then you can either set `--patches` argument to be low (as low as 4 or 8). Also make sure to adjust the scales and the box sizes according to the dataset.

**Comment by hendl** [comment]
Ok and how many images would you suggest?

**Comment by pvskand** [comment]
You can initially try dataset size similar to ST_PartA and then increase the dataset size depending on the performance.
