### ISSUE TITLE
Is error_function files wrong?

### ISSUE THREAD

**Issue by aboy2018** [val-iisc/lsc-cnn#2]
When I run a test code? This is a matter. Is the environment must be a ubuntu or other error? Thanks!

(pytorch) E:\example\LSC-CNN\lsc-cnn>python main.py --dataset="partb" --gpu=0 -skip-init-tests --start-epoch=24 --threshold=0.25
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from error_function import offset_sum
ModuleNotFoundError: No module named 'error_function'

**Comment by pvskand** [comment]
In order to create `error_function.so`, you'd have to run 
```
cd utils/mle_function
./script.sh
```
These commands are mentioned in the `README.md` in [this](https://github.com/val-iisc/lsc-cnn#for-testing-on-qnrf) section.

**Comment by aboy2018** [comment]
> In order to create `error_function.so`, you'd have to run
> 
> ```
> cd utils/mle_function
> ./script.sh
> ```
> 
> These commands are mentioned in the `README.md` in [this](https://github.com/val-iisc/lsc-cnn#for-testing-on-qnrf) section.

Thanks!

> In order to create `error_function.so`, you'd have to run
> 
> ```
> cd utils/mle_function
> ./script.sh
> ```
> 
> These commands are mentioned in the `README.md` in [this](https://github.com/val-iisc/lsc-cnn#for-testing-on-qnrf) section.

Thanks! 

> In order to create `error_function.so`, you'd have to run
> 
> ```
> cd utils/mle_function
> ./script.sh
> ```
> 
> These commands are mentioned in the `README.md` in [this](https://github.com/val-iisc/lsc-cnn#for-testing-on-qnrf) section.

Thanks for your reply!Can you upload the "requirements.txt" file? My environment  is always wrong.

**Comment by pvskand** [comment]
I've uploaded it. There was some problem earlier while committing my code. I've fixed it. Please check now.

**Comment by aboy2018** [comment]
> I've uploaded it. There was some problem earlier while committing my code. I've fixed it. Please check now.



> check

Thank you!

**Comment by sanakousar00** [comment]
cd utils/mle_function
./script.sh

ye run kro to setup.py ka error deta hai 
setup.py run kro to
