### ISSUE TITLE
How to optimize the bounding box?

### ISSUE THREAD

**Issue by HuynhKEn** [val-iisc/lsc-cnn#22]
Hello
I am trying to use your model to count the number of crab larvae, but I have the problem that the boxes that appear so bad are often out of place, how to optimize the boxes. Please help me because I'm making a graduation project.
result in dump/tesst
[https://ibb.co/2gfqyZm]()
but inference:
https://ibb.co/6F9Y54j

**Comment by pvskand** [comment]
Hi,
I can't view this link - https://ibb.co/2gfqyZm  -- It points me back to this page.
Additionally, did you train LSC-CNN on the crab larvae dataset?
