### ISSUE TITLE
how to generate the GT of UCF_QNRF dataset?

### ISSUE THREAD

**Issue by dk-liang** [val-iisc/lsc-cnn#24]
when I run `python main.py --dataset="ucfqnrf" --gpu=2`, there are some errors.

/home/xuwei/miniconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'error_function' does not match runtime version 3.7
  return f(*args, **kwds)
In data_reader.__init__: Can't read meta data in /data/weixu/qnrf_dotmaps_predictionScale_2; call create_dataset_files.
{'test': ['/data/weixu/UCF-QNRF_ECCV18/Test', '/data/weixu/UCF-QNRF_ECCV18/Test'], 'train': ['/data/weixu/UCF-QNRF_ECCV18/Train', '/data/weixu/UCF-QNRF_ECCV18/Train']} <data_reader.DataReader object at 0x7f8a6cd3b790>
CREATING DATASET...
In data_reader.create_dataset_files: Deleted old /data/weixu/qnrf_dotmaps_predictionScale_2/test.
In data_reader.create_dataset_files: /data/weixu/qnrf_dotmaps_predictionScale_2/test created.
In data_reader.create_dataset_files: Deleted old /data/weixu/qnrf_dotmaps_predictionScale_2/train.
In data_reader.create_dataset_files: /data/weixu/qnrf_dotmaps_predictionScale_2/train created.
In data_reader.create_dataset_files: Deleted old /data/weixu/qnrf_dotmaps_predictionScale_2/test_valid.
In data_reader.create_dataset_files: /data/weixu/qnrf_dotmaps_predictionScale_2/test_valid created.
Processing img_0001.jpg ...
Traceback (most recent call last):
  File "/home/xuwei/miniconda3/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 31, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/data/weixu/UCF-QNRF_ECCV18/Test/GT_img_0001.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1110, in <module>
    train()
  File "main.py", line 1029, in train
    test_batch_size=4)
  File "/home/xuwei/projects/synchronous/lsc-cnn-master/data_reader.py", line 200, in create_dataset_files
    self._dump_all_test_images(set_name)
  File "/home/xuwei/projects/synchronous/lsc-cnn-master/data_reader.py", line 827, in _dump_all_test_images
    data = self._read_image_and_gt_prediction(paths, file_name, kernel)
  File "/home/xuwei/projects/synchronous/lsc-cnn-master/data_reader.py", line 790, in _read_image_and_gt_prediction
    'GT_' + tmp + '.mat'))
  File "/home/xuwei/miniconda3/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/xuwei/miniconda3/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 62, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/home/xuwei/miniconda3/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 37, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '/data/weixu/UCF-QNRF_ECCV18/Test/GT_img_0001.mat'

**Comment by pvskand** [comment]
Hello,
I think the error says it all. The file you've mentioned doesn't exists in the shown path. Can you verify if `/data/weixu/UCF-QNRF_ECCV18/Test` is a valid path and if `GT_img_0001.mat` exists? Let me know if you still run into problems.

**Comment by dk-liang** [comment]
> Hello,
> I think the error says it all. The file you've mentioned doesn't exist in the shown path. Can you verify if `/data/weixu/UCF-QNRF_ECCV18/Test` is a valid path and if `GT_img_0001.mat` exists? Let me know if you still run into problems.

I have solved the problem. The reason is that the GT file name of ShanghaiTech is 'GT_IMG_xx.mat', and UCF-QNRF is 'img_xxxx_ann.mat'.

**Comment by ruchikalalit** [comment]
I am not able to execute the code for ucf-qnrf dataset, as I am getting the following error

In data_reader.init: Can't read meta data in ../dataset/qnrf_dotmaps_predictionScale_2; call genDatasetFiles.

{'test': ['../dataset/UCF-QNRF_ECCV18/Test/images', '../dataset/UCF-QNRF_ECCV18/Test/ground_truth'], 'train': ['../dataset/UCF-QNRF_ECCV18/Train/images', '../dataset/UCF-QNRF_ECCV18/Train/ground_truth']} <readData.DataReader object at 0x0000019C881DFE88>
CREATING DATASET...
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\test.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\test created.
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\train.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\train created.
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\test_valid.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\test_valid created.
Processing img_0001.jpg ...
Traceback (most recent call last):
File "D:/crowd_count_code_sumit/crowd_code/mainPro.py", line 1122, in
train()
File "D:/crowd_count_code_sumit/crowd_code/mainPro.py", line 1015, in train
test_batch_size=1)
File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 198, in genDatasetFiles
self._dump_all_test_images(set_name)
File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 824, in _dump_all_test_images
data = self._read_image_and_gt_prediction(paths, file_name, kernel)
File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 788, in _read_image_and_gt_prediction
gt_annotation_points = data_mat['image_info'][0, 0]['location'][0, 0]
KeyError: 'image_info'

Process finished with exit code 1

can you please help in removing this error
