### ISSUE TITLE
How to train models with rectangle box annotations in LSC-CNN ?

### ISSUE THREAD

**Issue by Captain-chan** [val-iisc/lsc-cnn#25]
I want to train a model with my custom dataset, which marked by rectangle box(Xmin,Ymin,Xmax,Ymax), what should i do ?

**Comment by pvskand** [comment]
LSC-CNN is a weakly-supervised model as the pseudo-box coordinates are obtained from ground truth annotation points. In order to run LSC-CNN on a dataset which has bounding box, you can obtain the center from box coordinates and feed this as input to the model.

**Comment by Captain-chan** [comment]
I actually want to know how to train LSC-CNN with boxes generated from actual box annotations instead of the head locations (LSC-CNN (Actual GT)) ？
