### ISSUE TITLE
Where do I find the head count detected for each image ?

### ISSUE THREAD

**Issue by MuteeullahBaig** [val-iisc/lsc-cnn#26]
I have followed all the instructions and ran the test (using the pre-trained models provided) on Part A using the command : 

python main.py --dataset="parta" --gpu=2 --start-epoch=13 --epochs=13 --threshold=0.21

I have got boxed images in models/dump_test.

But I want to know the efficiency of this model (ground truth vs detected head count, as presented on the page 11 of the paper  ). 

- If I have to compute it, how can I ?

- If it is already computed, where can I find it ?

**Comment by ruchikalalit** [comment]
@Muteeullah Baig, are you able to execute the code for ucf-qnrf dataset, as I am getting the following error

In data_reader.__init__: Can't read meta data in ../dataset/qnrf_dotmaps_predictionScale_2; call genDatasetFiles.

{'test': ['../dataset/UCF-QNRF_ECCV18/Test/images', '../dataset/UCF-QNRF_ECCV18/Test/ground_truth'], 'train': ['../dataset/UCF-QNRF_ECCV18/Train/images', '../dataset/UCF-QNRF_ECCV18/Train/ground_truth']} <readData.DataReader object at 0x0000019C881DFE88>
CREATING DATASET...
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\test.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\test created.
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\train.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\train created.
In data_reader.genDatasetFiles: Deleted old ../dataset/qnrf_dotmaps_predictionScale_2\test_valid.
In data_reader.genDatasetFiles: ../dataset/qnrf_dotmaps_predictionScale_2\test_valid created.
Processing img_0001.jpg ...
Traceback (most recent call last):
  File "D:/crowd_count_code_sumit/crowd_code/mainPro.py", line 1122, in <module>
    train()
  File "D:/crowd_count_code_sumit/crowd_code/mainPro.py", line 1015, in train
    test_batch_size=1)
  File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 198, in genDatasetFiles
    self._dump_all_test_images(set_name)
  File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 824, in _dump_all_test_images
    data = self._read_image_and_gt_prediction(paths, file_name, kernel)
  File "D:\crowd_count_code_sumit\crowd_code\readData.py", line 788, in _read_image_and_gt_prediction
    gt_annotation_points = data_mat['image_info'][0, 0]['location'][0, 0]
KeyError: 'image_info'

Process finished with exit code 1

can you please help in removing this error

**Comment by pvskand** [comment]
The function `calculate_metrics` has the localization metrics and is being called here - https://github.com/val-iisc/lsc-cnn/blob/master/main.py#L671
