### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by aboy2018** [val-iisc/lsc-cnn#3]
I notice that "main.py" file don't have "skip-init-tests" parameter. It has only code about training the model.How to test the "scale_4_epoch_24.pth"?

usage: main.py [-h] [--epochs N] [--gpu GPU] [--start-epoch N] [-b N]
               [--patches N] [--dataset DATASET] [--lr LR] [--momentum M]
               [--threshold M] [--weight-decay W] [--mle] [--lsccnn]
               [--trained-model PATH [PATH ...]]

**Comment by hxy1181501030** [comment]
I have the same question.

**Comment by Adhders** [comment]
same question

**Comment by pvskand** [comment]
Sorry for the delay. Please check now. The instructions have been updated.
