### ISSUE TITLE
Is there a way to run this model on an amd gpu setup? 

### ISSUE THREAD

**Issue by ilulale** [val-iisc/lsc-cnn#32]
I have an amd setup and i wanted to run this model. The docker setup uses Nvidia docker, is there a way to run this on an amd gpu?

**Comment by pasquale90** [comment]
For me that I don; t use docker but ubuntu instead, it runs just fine. 

ps : Have to be linux though since there 's a .so library file, which I was actually curious if it could be recompiled to run on Windows too..

**Comment by pvskand** [comment]
Hi, I haven't tried it on a windows system and the code is tested only on ubuntu. Also, docker is not essential as long as you install the requirements.

I'm closing this issue for now. Feel free to re-open it.
