### ISSUE TITLE
why skip some points in test model,and why are the predicted results and ground_truth the same?

### ISSUE THREAD

**Issue by aboy2018** [val-iisc/lsc-cnn#4]
In my test process:
Processing IMG_400.jpg ...
In data_reader.create_heatmap: Error in annotations; 1 point(s) skipped.
Processing IMG_44.jpg ...
Processing IMG_54.jpg ...
In data_reader.create_heatmap: Error in annotations; 1 point(s) skipped.
Processing IMG_59.jpg ...
Processing IMG_65.jpg ...
In data_reader.create_heatmap: Error in annotations; 2 point(s) skipped.

My predicted results' paths is "/home4/shuai/projects/LSC-CNN/dataset/stpartb_dotmaps_predscale0.5_rgb_ddcnn++_test/test/1/"
I notice that  the predicted counts and ground_truth is the same results.

Can you answer my question?Thanks.

**Comment by pvskand** [comment]
Hi,
Since you don't have the dataset already dumped, it will do it.
For testing, you need to run the command again.
