### ISSUE TITLE
How to make it faster?

### ISSUE THREAD

**Issue by anant15** [val-iisc/lsc-cnn#8]
The current model takes around 0.5 seconds on an image on RTX 2080 8 GB GPU. Are there are ways to make it run faster? May be change the backbone network or something else that you can suggest? 

I am fine having not so accurate result but I want to run it lets say at around 10 fps. Any help or suggestions will be appreciated.

**Comment by pvskand** [comment]
Decreasing the number of scales of LSC-CNN might work decently well for sparse crowds but it quiet depends on the use case. But we're in the process of improving the model and would soon update the repository.

In case you have questions about reducing the number of scales, please mail at `pvskand <at> protonmail <dot> com`.

**Comment by anant15** [comment]
When can we expect the improvements in the model being reflected here?
